### ISSUE TITLE
Wrong Padding

### ISSUE THREAD

**Issue by valentinwust** [anders-biostat/metdense#1]
I think the padding currently doesnt perform as specified. It seems like it only pads the data for a full chromosome into four byte blocks, instead of every row.

Also, I think you added the data or positions offset in the header when the rest was already done? Because additionally there seems to be a four byte discreptancy in how long the data block is, and how long it should be according to the padding per chromosome. Maybe you forgot to change something and it overwrites the last four data bytes with the positions block?

**Comment by simon-anders** [comment]
I've just fixed the first part.

As for the second one: I've added a second UInt32 in the Header block (there is now start of Data Block _and_ of Chromsome Block). Have you counted that one in? If so, I have to check again.

**Comment by simon-anders** [comment]
Wait, commit dbab289a should fix the second part of the issue, too.
Could you check, please, and close the issue if it does? Thanks.

**Comment by valentinwust** [comment]
I only take the difference between the start of the data and positions blocks as given in the file, so the length of the header block shouldn't really be relevant for that test.

Did you create a new test file or should I?

**Comment by valentinwust** [comment]
Could you generate a new test file? I can't find the relevant data on papagei.

I don't need to assume anything about the header block, I just take the difference between start of the data and the positions block as given in the file.

PS: <del>I already wrote this yesterday, but apparently forgot to send it.</del> Or not.

**Comment by valentinwust** [comment]
You were right, the issue is fixed now.
